name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Tejendra
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "dist"